export {default as About} from './about/About';
export {default as Academics} from './academics/Academics';
export {default as Admissions} from './admissions/Admissions';
export {default as Alumini} from './alumini/Alumini';
export {default as Calender} from './calender/Calender';
export {default as Gallery} from './gallery/Gallery';
export {default as Home} from './gallery/Gallery';
export {default as News} from './news/News';
export {default as Contact} from './contact/Contact'
